### ISSUE TITLE
gapi error while requiring

### ISSUE THREAD

**Issue by donny08** [phated/node-gapi#3]
when i require gapi i.e require('gapi') i'm getting below error
Error: Use CoffeeScript.register() or require the coffee-script/register module
to require .coffee.md files.
  at Object.base.(anonymous function) [as .coffee](D:BitBucketaerod-social-oa
uthnode_modulesgapinode_modulescoffee-scriptlibcoffee-scriptcoffee-script
.js:215:27)

**Comment by phated** [comment]
This library is extremely old and google changed the APIs it used.  I would suggest finding a different module.  Sorry.

**Comment by donny08** [comment]
Hey can you suggest me the module!!!
