### ISSUE TITLE
Unable to resolve module ./lib/gapi.coffee

### ISSUE THREAD

**Issue by sirajudheen53** [phated/node-gapi#4]
I am trying GAPI in one of my react native projects.

I have installed GAPI through command - npm install gapi
But when I import gapi in my project I got an error message in simulator which shows - "unable to resolve module ./lob.gapi.coffee from /users/***/node_modules/gapi/index.js Directory /users/**/node_modules/gapi/lib/gapi.coffee doesnot exist"

But in the file system I can see gapi.coffee file is present is there.

**Comment by phated** [comment]
This module is severely unmaintained. Don't use it. I believe Google released an official node library for their APIs.

**Comment by sirajudheen53** [comment]
But still google sample code uses gapi client for Javascript environment.

Reference: https://developers.google.com/api-client-library/javascript/start/start-js

Can you please identify why I am showing coffee.scipt file is missing ?

**Comment by phated** [comment]
That is NOT this library.
